export default {
  ext: 'ext.',
  country: 'Država telefonskog broja',
  phone: 'Telefon',
  AB: 'Abhazija',
  AC: 'Otok Uzašašća',
  AD: 'Andora',
  AE: 'Ujedinjeni Arapski Emirati',
  AF: 'Afganistan',
  AG: 'Antigva i Barbuda',
  AI: 'Angvila',
  AL: 'Albanija',
  AM: 'Armenija',
  AO: 'Angola',
  AQ: 'Antarktika',
  AR: 'Argentina',
  AS: 'Američka Samoa',
  AT: 'Austrija',
  AU: 'Australija',
  AW: 'Aruba',
  AX: 'Alandski otoci',
  AZ: 'Azerbejdžan',
  BA: 'Bosna i Hercegovina',
  BB: 'Barbados',
  BD: 'Bangladeš',
  BE: 'Belgija',
  BF: 'Burkina Faso',
  BG: 'Bugarska',
  BH: 'Bahrein',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'Sveti Barthélemy',
  BM: 'Bermuda',
  BN: 'Brunej Darusalam',
  BO: 'Bolivija',
  BQ: 'Bonaire, Sveti Eustazije i Saba',
  BR: 'Brazil',
  BS: 'Bahami',
  BT: 'Butan',
  BV: 'Otok Bouvet',
  BW: 'Bocvana',
  BY: 'Bjelorusija',
  BZ: 'Belize',
  CA: 'Kanada',
  CC: 'Kokosovi (Keelingovi) otoci',
  CD: 'Kongo, Demokratska Republika',
  CF: 'Srednjoafrička Republika',
  CG: 'Kongo',
  CH: 'Švicarska',
  CI: 'Obala Bjelokosti',
  CK: 'Cookovi otoci',
  CL: 'Čile',
  CM: 'Kamerun',
  CN: 'Kina',
  CO: 'Kolumbija',
  CR: 'Kostarika',
  CU: 'Kuba',
  CV: 'Kabo Verde',
  CW: 'Curaçao',
  CX: 'Božićni otok',
  CY: 'Cipar',
  CZ: 'Češka',
  DE: 'Njemačka',
  DJ: 'Džibuti',
  DK: 'Danska',
  DM: 'Dominika',
  DO: 'Dominikanska Republika',
  DZ: 'Alžir',
  EC: 'Ekvador',
  EE: 'Estonija',
  EG: 'Egipat',
  EH: 'Zapadna Sahara',
  ER: 'Eritreja',
  ES: 'Španjolska',
  ET: 'Etiopija',
  FI: 'Finska',
  FJ: 'Fidži',
  FK: 'Falklandski otoci',
  FM: 'Savezne Države Mikronezije',
  FO: 'Farski otoci',
  FR: 'Francuska',
  GA: 'Gabon',
  GB: 'Ujedinjeno Kraljevstvo',
  GD: 'Grenada',
  GE: 'Gruzija',
  GF: 'Francuska Gvajana',
  GG: 'Guernsey',
  GH: 'Gana',
  GI: 'Gibraltar',
  GL: 'Grenland',
  GM: 'Gambija',
  GN: 'Gvineja',
  GP: 'Gvadalupa',
  GQ: 'Ekvatorijalna Gvineja',
  GR: 'Grčka',
  GS: 'Južna Georgia i otoci Južni Sandwich',
  GT: 'Gvatemala',
  GU: 'Guam',
  GW: 'Gvineja Bisau',
  GY: 'Gvajana',
  HK: 'Hong Kong',
  HM: 'Heard Island i McDonald Islands',
  HN: 'Honduras',
  HR: 'Hrvatska',
  HT: 'Haiti',
  HU: 'Mađarska',
  ID: 'Indonezija',
  IE: 'Irska',
  IL: 'Izrael',
  IM: 'Otok Man',
  IN: 'Indija',
  IO: 'Britanski teritorij Indijskog oceana',
  IQ: 'Irak',
  IR: 'Iran',
  IS: 'Island',
  IT: 'Italija',
  JE: 'Dres',
  JM: 'Jamajka',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenija',
  KG: 'Kirgistan',
  KH: 'Kambodža',
  KI: 'Kiribati',
  KM: 'Komori',
  KN: 'Sveti Kristofor i Nevis',
  KP: 'Sjeverna Koreja',
  KR: 'Južna Koreja',
  KW: 'Kuvajt',
  KY: 'Kajmanski otoci',
  KZ: 'Kazahstan',
  LA: 'Laos',
  LB: 'Libanon',
  LC: 'Sveta Lucija',
  LI: 'Lihtenštajn',
  LK: 'Šri Lanka',
  LR: 'Liberija',
  LS: 'Lesoto',
  LT: 'Litva',
  LU: 'Luksemburg',
  LV: 'Latvija',
  LY: 'Libija',
  MA: 'Maroko',
  MC: 'Monaco',
  MD: 'Moldavija',
  ME: 'Crna Gora',
  MF: 'Sveti Martin (francuski dio)',
  MG: 'Madagaskar',
  MH: 'Maršalovi otoci',
  MK: 'Sjeverna Makedonija',
  ML: 'Mali',
  MM: 'Mjanmar',
  MN: 'Mongolija',
  MO: 'Makao',
  MP: 'Sjeverno Marijansko otočje',
  MQ: 'Martinik',
  MR: 'Mauritanija',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauricijus',
  MV: 'Maldivi',
  MW: 'Malavi',
  MX: 'Meksiko',
  MY: 'Malezija',
  MZ: 'Mozambik',
  NA: 'Namibija',
  NC: 'Nova Kaledonija',
  NE: 'Niger',
  NF: 'Otok Norfolk',
  NG: 'Nigerija',
  NI: 'Nikaragva',
  NL: 'Nizozemska',
  NO: 'Norveška',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'Novi Zeland',
  OM: 'Oman',
  OS: 'Južna Osetija',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'Francuska Polinezija',
  PG: 'Papua Nova Gvineja',
  PH: 'Filipini',
  PK: 'Pakistan',
  PL: 'Poljska',
  PM: 'Sveti Pjer i Mikelon',
  PN: 'Pitcairn',
  PR: 'Portoriko',
  PS: 'Palestina',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paragvaj',
  QA: 'Katar',
  RE: 'ponovno okupljanje',
  RO: 'Rumunija',
  RS: 'Srbija',
  RU: 'Rusija',
  RW: 'Ruanda',
  SA: 'Saudijska Arabija',
  SB: 'Salomonski otoci',
  SC: 'Sejšeli',
  SD: 'Sudan',
  SE: 'Švedska',
  SG: 'Singapur',
  SH: 'Sveta Helena',
  SI: 'Slovenija',
  SJ: 'Svalbard i Jan Mayen',
  SK: 'Slovačka',
  SL: 'Sijera Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalija',
  SR: 'Surinam',
  SS: 'Južni Sudan',
  ST: 'Sao Tome i Principe',
  SV: 'El Salvador',
  SX: 'Sent Maarten',
  SY: 'Sirija',
  SZ: 'Svaziland',
  TA: 'Tristan da Cunha',
  TC: 'Otočje Turks i Caicos',
  TD: 'Čad',
  TF: 'Francuski južni teritoriji',
  TG: 'Togo',
  TH: 'Tajland',
  TJ: 'Tadžikistan',
  TK: 'Tokelau',
  TL: 'Istočni Timor',
  TM: 'Turkmenistan',
  TN: 'Tunis',
  TO: 'Laka dvokolica',
  TR: 'Turska',
  TT: 'Trinidad i Tobago',
  TV: 'Tuvalu',
  TW: 'Tajvan',
  TZ: 'Tanzanija',
  UA: 'Ukrajina',
  UG: 'Uganda',
  UM: 'Manji udaljeni otoci Sjedinjenih Država',
  US: 'Sjedinjene Države',
  UY: 'Urugvaj',
  UZ: 'Uzbekistan',
  VA: 'Sveta Stolica (država Vatikan)',
  VC: 'Sveti Vincent i Grenadini',
  VE: 'Venezuela',
  VG: 'Djevičanski otoci, Britanski',
  VI: 'Djevičanski otoci, SAD',
  VN: 'Vijetnam',
  VU: 'Vanuatu',
  WF: 'Wallis i Futuna',
  WS: 'Samoa',
  XK: 'Kosovo',
  YE: 'Jemen',
  YT: 'Mayotte',
  ZA: 'Južna Afrika',
  ZM: 'Zambija',
  ZW: 'Zimbabve',
  ZZ: 'International',
} as const;
