name: Deploy to FTP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: develop

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Adjust this to your required Node.js version

    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Check Code
      run: npm run check
      working-directory: ./frontend

    - name: Build Project
      run: npm run build:staging
      working-directory: ./frontend

    # - name: "Deploy"
    #   uses: milanmk/actions-file-deployer@master
    #   with:
    #     remote-protocol: "sftp"
    #     remote-host: ${{ secrets.FTP_SERVER }}
    #     remote-port: 21
    #     remote-user: ${{ secrets.FTP_USERNAME }}
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     local-path: './frontend/dist'
    #     remote-path: ${{ secrets.FTP_REMOTE_PATH }}

    - name: Deploy
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 21
        source: "./frontend/dist/*"
        target: ${{ secrets.FTP_REMOTE_PATH }}
